### ISSUE TITLE
Feature Request: Add get_domain_for functionality

### ISSUE THREAD

**Issue by mcneely** [platformsh/config-reader-php#5]
In [https://docs.platform.sh/configuration/routes.html](https://docs.platform.sh/configuration/routes.html) there's a function to pull routes by id. It would be nice if it was added to this package. That allows us to isolated platform related code as a dependency.

**Comment by Crell** [comment]
Hi Paul.  We're actually nearly complete with a massive overhaul of all of our client libraries.  You can see what the v2 is going to look like in PR #4.  It's not quite done but should be out next week, I imagine.  It includes a bunch of improvements, including the ability to get a route by its ID.
